import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Web3Modal from 'web3modal';
import { ethers,providers } from 'ethers';
import { useEffect,useState, useRef } from 'react';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const[walletConnected, setWalletConnected] = useState(false);
  const web3ModalRef = useRef();
  const[ens, setENS] = useState("");
  const[address, setAddress] = useState("");

  const getProviderOrSigner = async() => {
  const provider = await web3ModalRef.current.connect();
  const web3Provider = new providers.Web3Provider(provider);
  const {chainId} = await web3Provider.getNetwork();
  if(chainId !== 5){
   window.alert("Change the network to goerli");
   throw new Error("Change the network to goerli")
  }
  const signer = web3Provider.getSigner();
  const address = await signer.getAddress();
  await setENSorAddress(address, web3Provider);
  return signer;
  }

  const connectWallet = async() => {
  try {
    await getProviderOrSigner();
    setWalletConnected(true);
  } catch (error) {
    console.log(error, "error");
  }
  }
  /* Sets the ENS name, if the current address has one or else it will
  set the address of the current account*/
const setENSorAddress = async(address, web3Provider) => {
let _ens = await web3Provider.lookupAddress(address);
if(_ens){
  setENS(_ens);
} else {
  setAddress(address);
}
}
const renderButton = () => {
  if(walletConnected){
    <div>Wallet Connected</div>
  } else {
    return(
      <button className={styles.button} onClick={connectWallet}>Connect wallet here</button>
    )
  }
}
useEffect(() => {
  if(!walletConnected){
    web3ModalRef.current = new Web3Modal({
      network: "goerli",
      providerOptions : {},
      disableInjectedProvider : false,
    });
    connectWallet();
  }
},[walletConnected]);

  return (


    <>
      <Head>
        <title>ENS DAPP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <div>
        <h1 className={styles.title}>
      Welcome to learnWeb3 punks {ens ? ens : address}
        </h1>
        <div className={styles.description}>
        Its an NFT collection for LearnWeb3 Punks.
        </div>
        {renderButton()}
       <div>
        <img className={styles.image} src='learnweb3punks.png'/>
       </div>
       <footer className={styles.footer}>
        Made with &#10084; by LearnWeb3 Punks
      </footer>
       </div>
      
      </main>
    </>
  )
}
